### ISSUE TITLE
Multi language support

### ISSUE THREAD

**Issue by GiacomoZ** [santa112358/cell_calendar#12]
Hello @santa112358,
Could you integrate support for changing the language of the month name and days of the week?

Thanks,
Giacomo

**Comment by santa112358** [comment]
@GiacomoZ 
Thank you for creating the issue!
Sure. Much better if the developers can change the text manually.

**Comment by GiacomoZ** [comment]
Thanks you!

**Comment by christian380** [comment]
i have a cuestion...
Do you have a approximate time to resolve this issue?

**Comment by santa112358** [comment]
@GiacomoZ @christian380 
Updated to v0.2.0 and you can customize labels on the calendar by the callbacks daysOfTheWeekBuilder and monthYearLabelBuilder. You can check the usage on readme or example. 
Thank you.
