### ISSUE TITLE
Can we change customize the textStyle of DateCell?

### ISSUE THREAD

**Issue by kakudenbuzo** [santa112358/cell_calendar#14]
Thank you for making this cool library.
I want to make the same UI as Google Calendar app, but there are some differences.
The biggest difference  for me is a textStyle for DateCell so I want to know if I can customize the textStyle of DateCell.
Thank you.

**Comment by santa112358** [comment]
@kakudenbuzo 
Thank you for the nice request. I've just added `dateTextStyle` in v0.3.0. 
Thank you.
