### ISSUE TITLE
Jump to a specific date 

### ISSUE THREAD

**Issue by kakudenbuzo** [santa112358/cell_calendar#17]
In my app, I would like to put 'jump to today' button.
Is there any way to jump to a specific date? If not could you add this feature please?
Thank you.

**Comment by santa112358** [comment]
@kakudenbuzo 
Thank you for the request.
There's no way to implement that with the current version, and I think that kind of feature(controls the paging of calendar) is necessary for this package, so please wait till I update.

**Comment by santa112358** [comment]
@kakudenbuzo 
Updated to v0.4.0 and you can implement the button to jump to specific date. Check the example -> https://github.com/santa112358/cell_calendar/blob/master/example/lib/main.dart

**Comment by kakudenbuzo** [comment]
Thank you very much!
