### ISSUE TITLE
Use DateFormat for monthYearLabelBuilder

### ISSUE THREAD

**Issue by locker5** [santa112358/cell_calendar#18]
First of all, thanks a lot for working on this project! Super useful!

I am having one problem for monthYearLabelBuilder.

I want to support i18n on my app, and using DateFormat library to make that happen.
For the calendar labels for the week of the day [S, M, T, W, T, F, S], I'm using DateFormat.E().format(DateTime.utc(2021, 2, 7)) etc, to support my usecase.

However, for monthYearLabelBuilder, I cannot get rid of the trailing comma at the end.
My code looks something like this now

`monthYearLabelBuilder: (datetime) {
const year = '';
final month = DateFormat.yMMM().format(datetime);`

which shows the text like below in the label
'2021年1月,' with a comma.

If I do 
`monthYearLabelBuilder: (datetime) {
final year = DateFormat.y().format(datetime);
final month = DateFormat.MMM().format(datetime);`

It will show '1月, 2021年 ' which is not so natural in Japanese.

Is it possible for you to support just the dateFormat, or create a way to get rid of the comma at the end?

Thank you very much!

**Comment by santa112358** [comment]
@locker5 Thank you for creating this issue. You can solve the problem by just fixing the widget to be returned in the builder.

I guess your code is now like this, which will show the label `1月, 2021年` because of the way of using the parameters in the Text widget: month and year. 

```dart
        monthYearLabelBuilder: (datetime) {
          final year = DateFormat.y().format(datetime); 
          final month = DateFormat.MMM().format(datetime)          
          return Padding(
            padding: const EdgeInsets.all(16.0),
            child: Text(
              /// The line you need to fix ↓
              "$month, $year",
              style: TextStyle(
                fontSize: 24,
                fontWeight: FontWeight.bold,
              ),
            ),
          );
        },
```

If you fix the line like this, it will return `2021年1月`.
```dart
        monthYearLabelBuilder: (datetime) {
          final year = DateFormat.y().format(datetime); 
          final month = DateFormat.MMM().format(datetime)          
          return Padding(
            padding: const EdgeInsets.all(16.0),
            child: Text(
              "$year$month",
              style: TextStyle(
                fontSize: 24,
                fontWeight: FontWeight.bold,
              ),
            ),
          );
        },
```

In addition, in this use case, you don't need to use two parameters, so I would change the code like this.

```dart
        monthYearLabelBuilder: (datetime) {
          final date =  DateFormat.yMMM().format(datetime);         
          return Padding(
            padding: const EdgeInsets.all(16.0),
            child: Text(
              date,
              style: TextStyle(
                fontSize: 24,
                fontWeight: FontWeight.bold,
              ),
            ),
          );
        },
```
If you still have any questions about this, feel free to ask on this issue.

Thank you

**Comment by locker5** [comment]
Sorry for the late respond! Yes I figured out now. Thanks for the advice!
