### ISSUE TITLE
Update provider to last version

### ISSUE THREAD

**Issue by endritgojanikodelabs** [santa112358/cell_calendar#30]
Because no versions of cell_calendar match >0.5.0+1 <0.6.0 and cell_calendar 0.5.0+1 depends on provider ^5.0.0, cell_calendar ^0.5.0+1 requires provider ^5.0.0.
And because flutter_bloc >=7.2.0 depends on provider ^6.0.0, cell_calendar ^0.5.0+1 is incompatible with flutter_bloc >=7.2.0.

**Comment by pedromorgan** [comment]
This project seems "quiet".. no updates since beginning of year.,.

**Comment by santa112358** [comment]
Sorry for very late response. This issue is solved on latest version.
